# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c04933ff6fe23df84bc022c5fe484535c2b3cca9be6766add80706d3717c8b54d28b8e82e725d03c80a99641ad7c2eeafcd0e367f19423bda998103636b7124

test:
  secret_key_base: b46e569777f0242f4825c20a86c43a596b2fe22e3ea6a4d9d86d8d1cc354d0741b0594c3da4c792ea41cba72cb010c3343ebfd90d190efa3d7d9d5501e2c8f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
